"""Fernet encryption for sensitive settings (API keys, webhooks, passwords).

Bootstrapping:
  - The symmetric key is read from ``MEDIAKEEPER_ENCRYPTION_KEY`` first, then
    from ``/data/.encryption_key`` (generated by ``entrypoint.sh`` on first
    launch). If neither exists (tests, local dev), a process-local key is
    generated so the module never throws on import — values stored with that
    ephemeral key won't survive a restart, which is fine for tests.

Data format on disk:
  - Clear values stay as-is (no prefix).
  - Encrypted values are prefixed with ``ENCRYPTED_PREFIX`` so ``decrypt_value``
    can safely be called on any stored value (plaintext passes through).
  - Writes to sensitive keys go through ``encrypt_value`` → ciphertext is
    always stored prefixed; reads are decrypted transparently.

Sensitive-key detection:
  - Tails: ``.api_key``, ``.password``, ``.token``, ``.secret``, ``.webhook_url``.
  - Add more suffixes in ``_SENSITIVE_SUFFIXES`` if new integrations land.
"""
from __future__ import annotations

import logging
import os
from functools import lru_cache
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

logger = logging.getLogger("mediakeeper.encryption")

ENCRYPTED_PREFIX = "fernet:v1:"

_KEY_ENV_VAR = "MEDIAKEEPER_ENCRYPTION_KEY"
_KEY_FILE_PATHS = (
    Path("/data/.encryption_key"),
    Path(os.environ.get("MEDIAKEEPER_ENCRYPTION_KEY_FILE", "")) if os.environ.get("MEDIAKEEPER_ENCRYPTION_KEY_FILE") else None,
)

_SENSITIVE_SUFFIXES = (
    ".api_key",
    ".password",
    ".token",
    ".secret",
    ".webhook_url",
)


def is_sensitive_key(key: str) -> bool:
    """Return True if a settings key should be encrypted at rest."""
    if not key:
        return False
    return any(key.endswith(suffix) for suffix in _SENSITIVE_SUFFIXES)


@lru_cache(maxsize=1)
def _load_fernet() -> Fernet:
    """Load the Fernet key from env, from the persisted file, or generate a
    process-local one as a last resort (tests / dev without the entrypoint)."""
    env_key = os.environ.get(_KEY_ENV_VAR, "").strip()
    if env_key:
        return Fernet(env_key.encode("ascii"))

    for path in _KEY_FILE_PATHS:
        if path and path.exists():
            data = path.read_text(encoding="ascii").strip()
            if data:
                return Fernet(data.encode("ascii"))

    generated = Fernet.generate_key()
    logger.warning(
        "[ENCRYPTION] No persistent key found (env/file absent). "
        "Using an ephemeral in-memory key — values written now will be "
        "unreadable after a restart. Set %s or mount /data/.encryption_key.",
        _KEY_ENV_VAR,
    )
    return Fernet(generated)


def encrypt_value(value: str) -> str:
    """Encrypt ``value`` and return a prefix-tagged ciphertext string.

    An empty string passes through untouched so we never store
    ``fernet:v1:<empty>`` and callers can compare settings with ``""``
    without having to decrypt first.
    """
    if not value:
        return ""
    if value.startswith(ENCRYPTED_PREFIX):
        return value
    fernet = _load_fernet()
    token = fernet.encrypt(value.encode("utf-8")).decode("ascii")
    return f"{ENCRYPTED_PREFIX}{token}"


def decrypt_value(value: str) -> str:
    """Decrypt a stored value. Plaintext (no prefix) is returned as-is so
    this function is safe to call on every read, even on legacy cleartext
    rows written before encryption was enabled."""
    if not value or not value.startswith(ENCRYPTED_PREFIX):
        return value
    fernet = _load_fernet()
    token = value[len(ENCRYPTED_PREFIX):]
    try:
        return fernet.decrypt(token.encode("ascii")).decode("utf-8")
    except InvalidToken:
        logger.error("[ENCRYPTION] Failed to decrypt a value (key rotated?). Returning empty string.")
        return ""
