import os
import bcrypt
import jwt
from pathlib import Path
from datetime import datetime, timedelta, timezone

# JWT secret key — priority:
#   1. JWT_SECRET_KEY env variable
#   2. /data/.jwt_secret file (auto-generated by entrypoint.sh)
SECRET_KEY = os.getenv("JWT_SECRET_KEY", "")
if not SECRET_KEY:
    _jwt_file = Path("/data/.jwt_secret")
    if _jwt_file.exists():
        SECRET_KEY = _jwt_file.read_text().strip()
if not SECRET_KEY:
    raise RuntimeError(
        "JWT_SECRET_KEY is not set and /data/.jwt_secret was not found. "
        "Set JWT_SECRET_KEY in .env or let the container generate it automatically."
    )
if len(SECRET_KEY.encode("utf-8")) < 32:
    raise RuntimeError("JWT_SECRET_KEY must contain at least 32 bytes for HS256.")

ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("JWT_EXPIRE_MINUTES", "60"))
EXTERNAL_AUTH_PASSWORD_SENTINEL = "__emby_auth__"


# ============================================
# PASSWORD
# ============================================

def hash_password(plain: str) -> str:
    """Hash and salt the password with bcrypt (cost factor 12)."""
    salt = bcrypt.gensalt(rounds=12)
    hashed = bcrypt.hashpw(plain.encode("utf-8"), salt)
    return hashed.decode("utf-8")


def verify_password(plain: str, hashed: str) -> bool:
    """Verify a plaintext password against its bcrypt hash."""
    try:
        return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))
    except ValueError:
        return False


def is_external_auth_only_password(hashed: str) -> bool:
    """
    Return True if the hash matches the sentinel password
    reserved for imported Emby/Jellyfin accounts.
    """
    if not hashed:
        return False
    return verify_password(EXTERNAL_AUTH_PASSWORD_SENTINEL, hashed)


def get_backoffice_admin_usernames() -> set[str]:
    """
    Return the list of accounts allowed to open a
    MediaKeeper backoffice session.
    """
    raw = os.getenv("MK_ADMIN_USERS", "admin")
    usernames = {
        part.strip()
        for part in raw.replace(";", ",").split(",")
        if part.strip()
    }
    return usernames or {"admin"}


def is_backoffice_admin(username: str) -> bool:
    return username in get_backoffice_admin_usernames()


def has_backoffice_access(
    username: str | None,
    hashed_password: str | None,
    *,
    is_active: bool,
) -> bool:
    """True iff this account can open a backoffice MediaKeeper session.

    Mirrors the gate enforced in /api/auth/login: user must be active,
    listed in MK_ADMIN_USERS, and own a real local password (not the
    Emby-only sentinel). Used by the Portal payload so the UI can hide
    the Dashboard shortcut for accounts that would only get a 401."""
    if not username or not is_active:
        return False
    if not is_backoffice_admin(username):
        return False
    if is_external_auth_only_password(hashed_password or ""):
        return False
    return True


def should_use_secure_cookies(request) -> bool:
    """
    Determine whether cookies should be marked Secure.
    - Explheret override via COOKIE_SECURE=true/false
    - Otherwise detected via X-Forwarded-Proto or the request scheme
    """
    override = os.getenv("COOKIE_SECURE", "").strip().lower()
    if override in ("1", "true", "yes", "on"):
        return True
    if override in ("0", "false", "no", "off"):
        return False

    headers = getattr(request, "headers", {}) or {}
    forwarded_proto = headers.get("x-forwarded-proto", "")
    if forwarded_proto:
        return forwarded_proto.split(",", 1)[0].strip().lower() == "https"

    scheme = getattr(getattr(request, "url", None), "scheme", "")
    return str(scheme).lower() == "https"


def get_cookie_samesite(request) -> str:
    """
    Determine which SameSite policy to apply.
    - Explheret override via COOKIE_SAMESITE=lax|strict|none
    - Default: ``lax`` (repo-native same-origin deployment)
    - ``none`` is only allowed if the cookie is ``Secure``
    """
    override = os.getenv("COOKIE_SAMESITE", "").strip().lower()
    if override in {"lax", "strict"}:
        return override
    if override == "none" and should_use_secure_cookies(request):
        return "none"
    return "lax"


# ============================================
# JWT (PyJWT)
# ============================================

def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
    """Create a signed JWT with expiration and issue date (iat)."""
    to_encode = data.copy()
    now = datetime.now(timezone.utc)
    expire = now + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire, "iat": now})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def decode_access_token(token: str) -> dict | None:
    """Decode and verify a JWT. Return None if invalid or expired."""
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except jwt.PyJWTError:
        return None
