import os
import bcrypt
import jwt
from pathlib import Path
from datetime import datetime, timedelta, timezone
from functools import lru_cache

from core.env_flags import env_int

# JWT secret key — priority:
#   1. JWT_SECRET_KEY env variable
#   2. /data/.jwt_secret file (auto-generated by entrypoint.sh)
# The .env.example placeholder is refused below: a copy-paste install must
# not boot with a publicly known secret (the length check alone passes it).
_ENV_EXAMPLE_PLACEHOLDER = "change-me-with-at-least-32-random-bytes"
SECRET_KEY = os.getenv("JWT_SECRET_KEY", "")
if not SECRET_KEY:
    _jwt_file = Path("/data/.jwt_secret")
    if _jwt_file.exists():
        SECRET_KEY = _jwt_file.read_text().strip()
if not SECRET_KEY:
    raise RuntimeError(
        "JWT_SECRET_KEY is not set and /data/.jwt_secret was not found. "
        "Set JWT_SECRET_KEY in .env or let the container generate it automatically."
    )
if SECRET_KEY == _ENV_EXAMPLE_PLACEHOLDER:
    raise RuntimeError(
        "JWT_SECRET_KEY is still set to the .env.example placeholder. Generate a "
        'real secret (python -c "import secrets; print(secrets.token_urlsafe(64))") '
        "or leave it unset to let the container auto-generate one."
    )
if len(SECRET_KEY.encode("utf-8")) < 32:
    raise RuntimeError("JWT_SECRET_KEY must contain at least 32 bytes for HS256.")

ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = env_int("JWT_EXPIRE_MINUTES", 60)
EXTERNAL_AUTH_PASSWORD_SENTINEL = "__emby_auth__"  # noqa: S105 -- sentinel marker for delegated auth, never used as a credential

# bcrypt 5 raises ``ValueError`` instead of silently truncating once the
# UTF-8 encoded password exceeds 72 bytes (algorithm limit). The constant
# is exposed so schema validators and callers stay in sync with the hash
# layer rather than duplicating the magic number.
MAX_BCRYPT_PASSWORD_BYTES = 72


class PasswordTooLongError(ValueError):
    """Raised by :func:`hash_password` when input exceeds the bcrypt limit."""


def password_byte_length(plain: str) -> int:
    """Return the UTF-8 byte length of a plaintext password."""
    return len(plain.encode("utf-8"))


def hash_password(plain: str) -> str:
    """Hash and salt the password with bcrypt (cost factor 12).

    Raises :class:`PasswordTooLongError` if ``plain`` exceeds
    :data:`MAX_BCRYPT_PASSWORD_BYTES` once UTF-8 encoded — bcrypt 5 would
    raise ``ValueError`` itself, but exposing a typed error keeps the API
    layer's mapping to a controlled HTTP response unambiguous.
    """
    encoded = plain.encode("utf-8")
    if len(encoded) > MAX_BCRYPT_PASSWORD_BYTES:
        raise PasswordTooLongError("password_too_long")
    salt = bcrypt.gensalt(rounds=12)
    hashed = bcrypt.hashpw(encoded, salt)
    return hashed.decode("utf-8")


def verify_password(plain: str, hashed: str) -> bool:
    """Verify a plaintext password against its bcrypt hash.

    Returns ``False`` instead of raising for inputs bcrypt cannot accept
    (oversized password, malformed hash) so login routes can never produce
    a 500 from user-controlled credential material.
    """
    encoded = plain.encode("utf-8")
    if len(encoded) > MAX_BCRYPT_PASSWORD_BYTES:
        return False
    try:
        return bcrypt.checkpw(encoded, hashed.encode("utf-8"))
    except ValueError:
        return False


def is_external_auth_only_password(hashed: str) -> bool:
    """
    Return True if the hash matches the sentinel password
    reserved for imported Emby/Jellyfin accounts.
    """
    if not hashed:
        return False
    return verify_password(EXTERNAL_AUTH_PASSWORD_SENTINEL, hashed)


@lru_cache(maxsize=8)
def _parse_admin_usernames(raw: str) -> frozenset[str]:
    usernames = {
        part.strip()
        for part in raw.replace(";", ",").split(",")
        if part.strip()
    }
    return frozenset(usernames or {"admin"})


def get_backoffice_admin_usernames() -> set[str]:
    """
    Return the list of accounts allowed to open a
    MediaKeeper backoffice session.

    The raw ``MK_ADMIN_USERS`` value is re-read on every call (cheap), but its
    parse is memoised per distinct value — so a live env change (the test suite
    monkeypatches it) is still honoured while the per-request split is cached.
    """
    return set(_parse_admin_usernames(os.getenv("MK_ADMIN_USERS", "admin")))


def is_backoffice_admin(username: str) -> bool:
    return username in get_backoffice_admin_usernames()


def has_backoffice_access(
    username: str | None,
    hashed_password: str | None,
    *,
    is_active: bool,
) -> bool:
    """True iff this account can open a backoffice MediaKeeper session.

    Mirrors the gate enforced in /api/auth/login: user must be active,
    listed in MK_ADMIN_USERS, and own a real local password (not the
    Emby-only sentinel). Used by the Portal payload so the UI can hide
    the Dashboard shortcut for accounts that would only get a 401."""
    if not username or not is_active:
        return False
    if not is_backoffice_admin(username):
        return False
    if is_external_auth_only_password(hashed_password or ""):
        return False
    return True


def should_use_secure_cookies(request) -> bool:
    """
    Determine whether cookies should be marked Secure.
    - Explicit override via COOKIE_SECURE=true/false
    - Otherwise consult ``request.url.scheme`` (already rewritten by
      ``ProxyHeadersMiddleware`` when the request comes from a trusted
      proxy with ``X-Forwarded-Proto: https``).
    """
    override = os.getenv("COOKIE_SECURE", "").strip().lower()
    if override in ("1", "true", "yes", "on"):
        return True
    if override in ("0", "false", "no", "off"):
        return False

    scheme = getattr(getattr(request, "url", None), "scheme", "")
    return str(scheme).lower() == "https"


def get_cookie_samesite(request) -> str:
    """
    Determine which SameSite policy to apply.
    - Explicit override via COOKIE_SAMESITE=lax|strict|none
    - Default: ``lax`` (repo-native same-origin deployment)
    - ``none`` is only allowed if the cookie is ``Secure``
    """
    override = os.getenv("COOKIE_SAMESITE", "").strip().lower()
    if override in {"lax", "strict"}:
        return override
    if override == "none" and should_use_secure_cookies(request):
        return "none"
    return "lax"


def create_access_token(data: dict, expires_delta: timedelta | None = None) -> str:
    """Create a signed JWT with expiration and issue date (iat)."""
    to_encode = data.copy()
    now = datetime.now(timezone.utc)
    expire = now + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire, "iat": now})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def decode_access_token(token: str) -> dict | None:
    """Decode and verify a JWT. Return None if invalid or expired."""
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except jwt.PyJWTError:
        return None


def is_token_valid_for_revocation_pivot(payload_iat, revocation_pivot) -> bool:
    """Return ``False`` when the JWT was issued before the revocation pivot.

    ``payload_iat`` accepts the raw ``iat`` claim (epoch int or float) and
    ``revocation_pivot`` accepts a ``datetime`` (naive values are treated
    as UTC for cross-backend safety) or ``None``. A ``None`` pivot means
    the account has never been revoked, so every token signed with the
    current key remains valid.
    """
    if revocation_pivot is None:
        return True
    if payload_iat is None:
        return False
    try:
        issued = datetime.fromtimestamp(int(payload_iat), tz=timezone.utc)
    except (TypeError, ValueError):
        return False
    pivot = revocation_pivot
    if pivot.tzinfo is None:
        pivot = pivot.replace(tzinfo=timezone.utc)
    return issued >= pivot
