"""
Tiered achievement definitions (Bronze → Mythique).

Each family has 1-5 tiers linked by `next_tier_id`. The frontend shows the
next unreached tier while hiding earlier ones from the grid.

condition_type values used here:
  - watch_movies, watch_series, streak_days, night_watch, marathon_hours
  - audio_languages, requests_created, rewatch_count, genre_diversity
  - subtitle_languages, weekend_plays, season_binge, library_explorer
  - chat_messages, leaderboard_top{10,5,3}, leaderboard_first
  - achievements_unlocked, profile_level, avatar_changed, member_years
  - title_equipped, tickets_created, decades_watched, total_watch_hours
  - requests_approved, series_completed, speed_runner, binge_session
  - genre_master, events_created, surprise_used
"""

STANDARD_DEFS: list[dict] = [
    # ═══ CINEPHILE (movies watched) ═══
    {"id": "movie_buff_1", "category": "watching", "name_key": "portal.achievements.movieBuff", "description_key": "portal.achievements.movieBuff_desc", "icon": "Film", "tier": 1, "xp_reward": 20, "threshold": 10, "condition_type": "watch_movies", "next_tier_id": "movie_buff_2", "secret": False, "sort_order": 10},
    {"id": "movie_buff_2", "category": "watching", "name_key": "portal.achievements.movieBuff", "description_key": "portal.achievements.movieBuff_desc", "icon": "Film", "tier": 2, "xp_reward": 50, "threshold": 30, "condition_type": "watch_movies", "next_tier_id": "movie_buff_3", "secret": False, "sort_order": 11},
    {"id": "movie_buff_3", "category": "watching", "name_key": "portal.achievements.movieBuff", "description_key": "portal.achievements.movieBuff_desc", "icon": "Film", "tier": 3, "xp_reward": 110, "threshold": 75, "condition_type": "watch_movies", "next_tier_id": "movie_buff_4", "secret": False, "sort_order": 12},
    {"id": "movie_buff_4", "category": "watching", "name_key": "portal.achievements.movieBuff", "description_key": "portal.achievements.movieBuff_desc", "icon": "Film", "tier": 4, "xp_reward": 220, "threshold": 200, "condition_type": "watch_movies", "next_tier_id": "movie_buff_5", "secret": False, "sort_order": 13},
    {"id": "movie_buff_5", "category": "watching", "name_key": "portal.achievements.movieBuff", "description_key": "portal.achievements.movieBuff_desc", "icon": "Film", "tier": 5, "xp_reward": 500, "threshold": 500, "condition_type": "watch_movies", "next_tier_id": None, "secret": False, "sort_order": 14},

    # ═══ SERIAL FAN (series watched) ═══
    {"id": "serial_fan_1", "category": "watching", "name_key": "portal.achievements.serialFan", "description_key": "portal.achievements.serialFan_desc", "icon": "Tv", "tier": 1, "xp_reward": 20, "threshold": 5, "condition_type": "watch_series", "next_tier_id": "serial_fan_2", "secret": False, "sort_order": 20},
    {"id": "serial_fan_2", "category": "watching", "name_key": "portal.achievements.serialFan", "description_key": "portal.achievements.serialFan_desc", "icon": "Tv", "tier": 2, "xp_reward": 50, "threshold": 15, "condition_type": "watch_series", "next_tier_id": "serial_fan_3", "secret": False, "sort_order": 21},
    {"id": "serial_fan_3", "category": "watching", "name_key": "portal.achievements.serialFan", "description_key": "portal.achievements.serialFan_desc", "icon": "Tv", "tier": 3, "xp_reward": 110, "threshold": 40, "condition_type": "watch_series", "next_tier_id": "serial_fan_4", "secret": False, "sort_order": 22},
    {"id": "serial_fan_4", "category": "watching", "name_key": "portal.achievements.serialFan", "description_key": "portal.achievements.serialFan_desc", "icon": "Tv", "tier": 4, "xp_reward": 220, "threshold": 100, "condition_type": "watch_series", "next_tier_id": "serial_fan_5", "secret": False, "sort_order": 23},
    {"id": "serial_fan_5", "category": "watching", "name_key": "portal.achievements.serialFan", "description_key": "portal.achievements.serialFan_desc", "icon": "Tv", "tier": 5, "xp_reward": 500, "threshold": 250, "condition_type": "watch_series", "next_tier_id": None, "secret": False, "sort_order": 24},

    # ═══ REGULAR (streak days) ═══
    {"id": "regular_1", "category": "dedication", "name_key": "portal.achievements.regular", "description_key": "portal.achievements.regular_desc", "icon": "Flame", "tier": 1, "xp_reward": 20, "threshold": 3, "condition_type": "streak_days", "next_tier_id": "regular_2", "secret": False, "sort_order": 30},
    {"id": "regular_2", "category": "dedication", "name_key": "portal.achievements.regular", "description_key": "portal.achievements.regular_desc", "icon": "Flame", "tier": 2, "xp_reward": 50, "threshold": 7, "condition_type": "streak_days", "next_tier_id": "regular_3", "secret": False, "sort_order": 31},
    {"id": "regular_3", "category": "dedication", "name_key": "portal.achievements.regular", "description_key": "portal.achievements.regular_desc", "icon": "Flame", "tier": 3, "xp_reward": 110, "threshold": 21, "condition_type": "streak_days", "next_tier_id": "regular_4", "secret": False, "sort_order": 32},
    {"id": "regular_4", "category": "dedication", "name_key": "portal.achievements.regular", "description_key": "portal.achievements.regular_desc", "icon": "Flame", "tier": 4, "xp_reward": 220, "threshold": 60, "condition_type": "streak_days", "next_tier_id": "regular_5", "secret": False, "sort_order": 33},
    {"id": "regular_5", "category": "dedication", "name_key": "portal.achievements.regular", "description_key": "portal.achievements.regular_desc", "icon": "Flame", "tier": 5, "xp_reward": 500, "threshold": 180, "condition_type": "streak_days", "next_tier_id": "regular_6", "secret": False, "sort_order": 34},
    {"id": "regular_6", "category": "dedication", "name_key": "portal.achievements.regular", "description_key": "portal.achievements.regular_desc", "icon": "Flame", "tier": 6, "xp_reward": 1200, "threshold": 365, "condition_type": "streak_days", "next_tier_id": None, "secret": False, "sort_order": 35},

    # ═══ ALL-NIGHTER (night watch 00:00-05:00) ═══
    {"id": "all_nighter_1", "category": "special", "name_key": "portal.achievements.allNighter", "description_key": "portal.achievements.allNighter_desc", "icon": "Moon", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "night_watch", "next_tier_id": "all_nighter_2", "secret": False, "sort_order": 40},
    {"id": "all_nighter_2", "category": "special", "name_key": "portal.achievements.allNighter", "description_key": "portal.achievements.allNighter_desc", "icon": "Moon", "tier": 2, "xp_reward": 50, "threshold": 10, "condition_type": "night_watch", "next_tier_id": "all_nighter_3", "secret": False, "sort_order": 41},
    {"id": "all_nighter_3", "category": "special", "name_key": "portal.achievements.allNighter", "description_key": "portal.achievements.allNighter_desc", "icon": "Moon", "tier": 3, "xp_reward": 110, "threshold": 30, "condition_type": "night_watch", "next_tier_id": "all_nighter_4", "secret": False, "sort_order": 42},
    {"id": "all_nighter_4", "category": "special", "name_key": "portal.achievements.allNighter", "description_key": "portal.achievements.allNighter_desc", "icon": "Moon", "tier": 4, "xp_reward": 220, "threshold": 75, "condition_type": "night_watch", "next_tier_id": "all_nighter_5", "secret": False, "sort_order": 43},
    {"id": "all_nighter_5", "category": "special", "name_key": "portal.achievements.allNighter", "description_key": "portal.achievements.allNighter_desc", "icon": "Moon", "tier": 5, "xp_reward": 500, "threshold": 200, "condition_type": "night_watch", "next_tier_id": None, "secret": False, "sort_order": 44},

    # ═══ MARATHONER (8h+ in a day) ═══
    {"id": "marathoner_1", "category": "special", "name_key": "portal.achievements.marathoner", "description_key": "portal.achievements.marathoner_desc", "icon": "Zap", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "marathon_hours", "next_tier_id": "marathoner_2", "secret": False, "sort_order": 50},
    {"id": "marathoner_2", "category": "special", "name_key": "portal.achievements.marathoner", "description_key": "portal.achievements.marathoner_desc", "icon": "Zap", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "marathon_hours", "next_tier_id": "marathoner_3", "secret": False, "sort_order": 51},
    {"id": "marathoner_3", "category": "special", "name_key": "portal.achievements.marathoner", "description_key": "portal.achievements.marathoner_desc", "icon": "Zap", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "marathon_hours", "next_tier_id": "marathoner_4", "secret": False, "sort_order": 52},
    {"id": "marathoner_4", "category": "special", "name_key": "portal.achievements.marathoner", "description_key": "portal.achievements.marathoner_desc", "icon": "Zap", "tier": 4, "xp_reward": 220, "threshold": 40, "condition_type": "marathon_hours", "next_tier_id": "marathoner_5", "secret": False, "sort_order": 53},
    {"id": "marathoner_5", "category": "special", "name_key": "portal.achievements.marathoner", "description_key": "portal.achievements.marathoner_desc", "icon": "Zap", "tier": 5, "xp_reward": 500, "threshold": 50, "condition_type": "marathon_hours", "next_tier_id": None, "secret": False, "sort_order": 54},

    # ═══ GLOBE-TROTTER (audio languages) ═══
    {"id": "globe_trotter_1", "category": "diversity", "name_key": "portal.achievements.globeTrotter", "description_key": "portal.achievements.globeTrotter_desc", "icon": "Globe", "tier": 1, "xp_reward": 20, "threshold": 3, "condition_type": "audio_languages", "next_tier_id": "globe_trotter_2", "secret": False, "sort_order": 60},
    {"id": "globe_trotter_2", "category": "diversity", "name_key": "portal.achievements.globeTrotter", "description_key": "portal.achievements.globeTrotter_desc", "icon": "Globe", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "audio_languages", "next_tier_id": "globe_trotter_3", "secret": False, "sort_order": 61},
    {"id": "globe_trotter_3", "category": "diversity", "name_key": "portal.achievements.globeTrotter", "description_key": "portal.achievements.globeTrotter_desc", "icon": "Globe", "tier": 3, "xp_reward": 110, "threshold": 8, "condition_type": "audio_languages", "next_tier_id": "globe_trotter_4", "secret": False, "sort_order": 62},
    {"id": "globe_trotter_4", "category": "diversity", "name_key": "portal.achievements.globeTrotter", "description_key": "portal.achievements.globeTrotter_desc", "icon": "Globe", "tier": 4, "xp_reward": 220, "threshold": 12, "condition_type": "audio_languages", "next_tier_id": "globe_trotter_5", "secret": False, "sort_order": 63},
    {"id": "globe_trotter_5", "category": "diversity", "name_key": "portal.achievements.globeTrotter", "description_key": "portal.achievements.globeTrotter_desc", "icon": "Globe", "tier": 5, "xp_reward": 500, "threshold": 20, "condition_type": "audio_languages", "next_tier_id": None, "secret": False, "sort_order": 64},

    # ═══ REQUESTER (requests created) ═══
    {"id": "requester_1", "category": "community", "name_key": "portal.achievements.requester", "description_key": "portal.achievements.requester_desc", "icon": "Send", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "requests_created", "next_tier_id": "requester_2", "secret": False, "sort_order": 70},
    {"id": "requester_2", "category": "community", "name_key": "portal.achievements.requester", "description_key": "portal.achievements.requester_desc", "icon": "Send", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "requests_created", "next_tier_id": "requester_3", "secret": False, "sort_order": 71},
    {"id": "requester_3", "category": "community", "name_key": "portal.achievements.requester", "description_key": "portal.achievements.requester_desc", "icon": "Send", "tier": 3, "xp_reward": 110, "threshold": 20, "condition_type": "requests_created", "next_tier_id": "requester_4", "secret": False, "sort_order": 72},
    {"id": "requester_4", "category": "community", "name_key": "portal.achievements.requester", "description_key": "portal.achievements.requester_desc", "icon": "Send", "tier": 4, "xp_reward": 220, "threshold": 50, "condition_type": "requests_created", "next_tier_id": "requester_5", "secret": False, "sort_order": 73},
    {"id": "requester_5", "category": "community", "name_key": "portal.achievements.requester", "description_key": "portal.achievements.requester_desc", "icon": "Send", "tier": 5, "xp_reward": 500, "threshold": 150, "condition_type": "requests_created", "next_tier_id": None, "secret": False, "sort_order": 74},

    # ═══ REWATCH KING (items rewatched 5+ times) ═══
    {"id": "rewatch_king_1", "category": "watching", "name_key": "portal.achievements.rewatchKing", "description_key": "portal.achievements.rewatchKing_desc", "icon": "RotateCcw", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "rewatch_count", "next_tier_id": "rewatch_king_2", "secret": False, "sort_order": 80},
    {"id": "rewatch_king_2", "category": "watching", "name_key": "portal.achievements.rewatchKing", "description_key": "portal.achievements.rewatchKing_desc", "icon": "RotateCcw", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "rewatch_count", "next_tier_id": "rewatch_king_3", "secret": False, "sort_order": 81},
    {"id": "rewatch_king_3", "category": "watching", "name_key": "portal.achievements.rewatchKing", "description_key": "portal.achievements.rewatchKing_desc", "icon": "RotateCcw", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "rewatch_count", "next_tier_id": "rewatch_king_4", "secret": False, "sort_order": 82},
    {"id": "rewatch_king_4", "category": "watching", "name_key": "portal.achievements.rewatchKing", "description_key": "portal.achievements.rewatchKing_desc", "icon": "RotateCcw", "tier": 4, "xp_reward": 220, "threshold": 30, "condition_type": "rewatch_count", "next_tier_id": "rewatch_king_5", "secret": False, "sort_order": 83},
    {"id": "rewatch_king_5", "category": "watching", "name_key": "portal.achievements.rewatchKing", "description_key": "portal.achievements.rewatchKing_desc", "icon": "RotateCcw", "tier": 5, "xp_reward": 500, "threshold": 75, "condition_type": "rewatch_count", "next_tier_id": None, "secret": False, "sort_order": 84},

    # ═══ ECLECTIC (genre diversity) ═══
    {"id": "eclectic_1", "category": "diversity", "name_key": "portal.achievements.eclectic", "description_key": "portal.achievements.eclectic_desc", "icon": "Target", "tier": 1, "xp_reward": 20, "threshold": 5, "condition_type": "genre_diversity", "next_tier_id": "eclectic_2", "secret": False, "sort_order": 90},
    {"id": "eclectic_2", "category": "diversity", "name_key": "portal.achievements.eclectic", "description_key": "portal.achievements.eclectic_desc", "icon": "Target", "tier": 2, "xp_reward": 50, "threshold": 8, "condition_type": "genre_diversity", "next_tier_id": "eclectic_3", "secret": False, "sort_order": 91},
    {"id": "eclectic_3", "category": "diversity", "name_key": "portal.achievements.eclectic", "description_key": "portal.achievements.eclectic_desc", "icon": "Target", "tier": 3, "xp_reward": 110, "threshold": 12, "condition_type": "genre_diversity", "next_tier_id": "eclectic_4", "secret": False, "sort_order": 92},
    {"id": "eclectic_4", "category": "diversity", "name_key": "portal.achievements.eclectic", "description_key": "portal.achievements.eclectic_desc", "icon": "Target", "tier": 4, "xp_reward": 220, "threshold": 16, "condition_type": "genre_diversity", "next_tier_id": "eclectic_5", "secret": False, "sort_order": 93},
    {"id": "eclectic_5", "category": "diversity", "name_key": "portal.achievements.eclectic", "description_key": "portal.achievements.eclectic_desc", "icon": "Target", "tier": 5, "xp_reward": 500, "threshold": 22, "condition_type": "genre_diversity", "next_tier_id": None, "secret": False, "sort_order": 94},

    # ═══ POLYGLOT (subtitle languages) ═══
    {"id": "polyglot_1", "category": "diversity", "name_key": "portal.achievements.polyglot", "description_key": "portal.achievements.polyglot_desc", "icon": "Subtitles", "tier": 1, "xp_reward": 20, "threshold": 2, "condition_type": "subtitle_languages", "next_tier_id": "polyglot_2", "secret": False, "sort_order": 100},
    {"id": "polyglot_2", "category": "diversity", "name_key": "portal.achievements.polyglot", "description_key": "portal.achievements.polyglot_desc", "icon": "Subtitles", "tier": 2, "xp_reward": 50, "threshold": 4, "condition_type": "subtitle_languages", "next_tier_id": "polyglot_3", "secret": False, "sort_order": 101},
    {"id": "polyglot_3", "category": "diversity", "name_key": "portal.achievements.polyglot", "description_key": "portal.achievements.polyglot_desc", "icon": "Subtitles", "tier": 3, "xp_reward": 110, "threshold": 7, "condition_type": "subtitle_languages", "next_tier_id": None, "secret": False, "sort_order": 102},

    # ═══ WEEKEND WARRIOR ═══
    {"id": "weekend_warrior_1", "category": "special", "name_key": "portal.achievements.weekendWarrior", "description_key": "portal.achievements.weekendWarrior_desc", "icon": "Gamepad2", "tier": 1, "xp_reward": 20, "threshold": 10, "condition_type": "weekend_plays", "next_tier_id": "weekend_warrior_2", "secret": False, "sort_order": 110},
    {"id": "weekend_warrior_2", "category": "special", "name_key": "portal.achievements.weekendWarrior", "description_key": "portal.achievements.weekendWarrior_desc", "icon": "Gamepad2", "tier": 2, "xp_reward": 50, "threshold": 25, "condition_type": "weekend_plays", "next_tier_id": "weekend_warrior_3", "secret": False, "sort_order": 111},
    {"id": "weekend_warrior_3", "category": "special", "name_key": "portal.achievements.weekendWarrior", "description_key": "portal.achievements.weekendWarrior_desc", "icon": "Gamepad2", "tier": 3, "xp_reward": 110, "threshold": 50, "condition_type": "weekend_plays", "next_tier_id": None, "secret": False, "sort_order": 112},

    # ═══ SEASON IN ONE GO ═══
    {"id": "season_binge_1", "category": "special", "name_key": "portal.achievements.seasonBinge", "description_key": "portal.achievements.seasonBinge_desc", "icon": "FastForward", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "season_binge", "next_tier_id": "season_binge_2", "secret": False, "sort_order": 120},
    {"id": "season_binge_2", "category": "special", "name_key": "portal.achievements.seasonBinge", "description_key": "portal.achievements.seasonBinge_desc", "icon": "FastForward", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "season_binge", "next_tier_id": "season_binge_3", "secret": False, "sort_order": 121},
    {"id": "season_binge_3", "category": "special", "name_key": "portal.achievements.seasonBinge", "description_key": "portal.achievements.seasonBinge_desc", "icon": "FastForward", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "season_binge", "next_tier_id": None, "secret": False, "sort_order": 122},

    # ═══ EXPLORER ═══
    {"id": "explorer_1", "category": "diversity", "name_key": "portal.achievements.explorer", "description_key": "portal.achievements.explorer_desc", "icon": "Compass", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "library_explorer", "next_tier_id": None, "secret": False, "sort_order": 130},

    # ═══ CHATTERBOX (chat messages) ═══
    {"id": "chatty_1", "category": "community", "name_key": "portal.achievements.chatty", "description_key": "portal.achievements.chatty_desc", "icon": "MessageCircle", "tier": 1, "xp_reward": 20, "threshold": 50, "condition_type": "chat_messages", "next_tier_id": "chatty_2", "secret": False, "sort_order": 140},
    {"id": "chatty_2", "category": "community", "name_key": "portal.achievements.chatty", "description_key": "portal.achievements.chatty_desc", "icon": "MessageCircle", "tier": 2, "xp_reward": 50, "threshold": 200, "condition_type": "chat_messages", "next_tier_id": "chatty_3", "secret": False, "sort_order": 141},
    {"id": "chatty_3", "category": "community", "name_key": "portal.achievements.chatty", "description_key": "portal.achievements.chatty_desc", "icon": "MessageCircle", "tier": 3, "xp_reward": 110, "threshold": 500, "condition_type": "chat_messages", "next_tier_id": None, "secret": False, "sort_order": 142},

    # ═══ COMPETITOR (monthly leaderboard position) ═══
    {"id": "competitor_1", "category": "ranking", "name_key": "portal.achievements.competitor", "description_key": "portal.achievements.competitor_desc", "icon": "Trophy", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "leaderboard_top10", "next_tier_id": "competitor_2", "secret": False, "sort_order": 150},
    {"id": "competitor_2", "category": "ranking", "name_key": "portal.achievements.competitor", "description_key": "portal.achievements.competitor_desc", "icon": "Trophy", "tier": 2, "xp_reward": 50, "threshold": 1, "condition_type": "leaderboard_top5", "next_tier_id": "competitor_3", "secret": False, "sort_order": 151},
    {"id": "competitor_3", "category": "ranking", "name_key": "portal.achievements.competitor", "description_key": "portal.achievements.competitor_desc", "icon": "Trophy", "tier": 3, "xp_reward": 110, "threshold": 1, "condition_type": "leaderboard_top3", "next_tier_id": "competitor_4", "secret": False, "sort_order": 152},
    {"id": "competitor_4", "category": "ranking", "name_key": "portal.achievements.competitor", "description_key": "portal.achievements.competitor_desc", "icon": "Trophy", "tier": 4, "xp_reward": 220, "threshold": 1, "condition_type": "leaderboard_first", "next_tier_id": "competitor_5", "secret": False, "sort_order": 153},
    {"id": "competitor_5", "category": "ranking", "name_key": "portal.achievements.competitor", "description_key": "portal.achievements.competitor_desc", "icon": "Trophy", "tier": 5, "xp_reward": 500, "threshold": 3, "condition_type": "leaderboard_first", "next_tier_id": "competitor_6", "secret": False, "sort_order": 154},
    {"id": "competitor_6", "category": "ranking", "name_key": "portal.achievements.competitor", "description_key": "portal.achievements.competitor_desc", "icon": "Trophy", "tier": 6, "xp_reward": 1200, "threshold": 12, "condition_type": "leaderboard_first", "next_tier_id": None, "secret": False, "sort_order": 155},

    # ═══ COLLECTOR (achievements unlocked) ═══
    {"id": "collector_1", "category": "meta", "name_key": "portal.achievements.collector", "description_key": "portal.achievements.collector_desc", "icon": "Award", "tier": 1, "xp_reward": 20, "threshold": 5, "condition_type": "achievements_unlocked", "next_tier_id": "collector_2", "secret": False, "sort_order": 160},
    {"id": "collector_2", "category": "meta", "name_key": "portal.achievements.collector", "description_key": "portal.achievements.collector_desc", "icon": "Award", "tier": 2, "xp_reward": 50, "threshold": 15, "condition_type": "achievements_unlocked", "next_tier_id": "collector_3", "secret": False, "sort_order": 161},
    {"id": "collector_3", "category": "meta", "name_key": "portal.achievements.collector", "description_key": "portal.achievements.collector_desc", "icon": "Award", "tier": 3, "xp_reward": 110, "threshold": 30, "condition_type": "achievements_unlocked", "next_tier_id": "collector_4", "secret": False, "sort_order": 162},
    {"id": "collector_4", "category": "meta", "name_key": "portal.achievements.collector", "description_key": "portal.achievements.collector_desc", "icon": "Award", "tier": 4, "xp_reward": 220, "threshold": 50, "condition_type": "achievements_unlocked", "next_tier_id": "collector_5", "secret": False, "sort_order": 163},
    {"id": "collector_5", "category": "meta", "name_key": "portal.achievements.collector", "description_key": "portal.achievements.collector_desc", "icon": "Award", "tier": 5, "xp_reward": 500, "threshold": 100, "condition_type": "achievements_unlocked", "next_tier_id": "collector_6", "secret": False, "sort_order": 164},
    {"id": "collector_6", "category": "meta", "name_key": "portal.achievements.collector", "description_key": "portal.achievements.collector_desc", "icon": "Award", "tier": 6, "xp_reward": 1200, "threshold": 200, "condition_type": "achievements_unlocked", "next_tier_id": None, "secret": False, "sort_order": 166},

    # ═══ VETERAN (profile level) ═══
    {"id": "veteran_1", "category": "meta", "name_key": "portal.achievements.veteran", "description_key": "portal.achievements.veteran_desc", "icon": "TrendingUp", "tier": 1, "xp_reward": 20, "threshold": 5, "condition_type": "profile_level", "next_tier_id": "veteran_2", "secret": False, "sort_order": 170},
    {"id": "veteran_2", "category": "meta", "name_key": "portal.achievements.veteran", "description_key": "portal.achievements.veteran_desc", "icon": "TrendingUp", "tier": 2, "xp_reward": 50, "threshold": 15, "condition_type": "profile_level", "next_tier_id": "veteran_3", "secret": False, "sort_order": 171},
    {"id": "veteran_3", "category": "meta", "name_key": "portal.achievements.veteran", "description_key": "portal.achievements.veteran_desc", "icon": "TrendingUp", "tier": 3, "xp_reward": 110, "threshold": 25, "condition_type": "profile_level", "next_tier_id": "veteran_4", "secret": False, "sort_order": 172},
    {"id": "veteran_4", "category": "meta", "name_key": "portal.achievements.veteran", "description_key": "portal.achievements.veteran_desc", "icon": "TrendingUp", "tier": 4, "xp_reward": 220, "threshold": 35, "condition_type": "profile_level", "next_tier_id": "veteran_5", "secret": False, "sort_order": 173},
    {"id": "veteran_5", "category": "meta", "name_key": "portal.achievements.veteran", "description_key": "portal.achievements.veteran_desc", "icon": "TrendingUp", "tier": 5, "xp_reward": 500, "threshold": 50, "condition_type": "profile_level", "next_tier_id": None, "secret": False, "sort_order": 174},

    # ═══ PHOTOGENIC (avatar changed) ═══
    {"id": "photogenic_1", "category": "meta", "name_key": "portal.achievements.photogenic", "description_key": "portal.achievements.photogenic_desc", "icon": "Camera", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "avatar_changed", "next_tier_id": None, "secret": False, "sort_order": 180},

    # ═══ OLD-TIMER (member for X years) ═══
    {"id": "longtime_member_1", "category": "dedication", "name_key": "portal.achievements.longtimeMember", "description_key": "portal.achievements.longtimeMember_desc", "icon": "Clock", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "member_years", "next_tier_id": "longtime_member_2", "secret": False, "sort_order": 185},
    {"id": "longtime_member_2", "category": "dedication", "name_key": "portal.achievements.longtimeMember", "description_key": "portal.achievements.longtimeMember_desc", "icon": "Clock", "tier": 2, "xp_reward": 50, "threshold": 2, "condition_type": "member_years", "next_tier_id": "longtime_member_3", "secret": False, "sort_order": 186},
    {"id": "longtime_member_3", "category": "dedication", "name_key": "portal.achievements.longtimeMember", "description_key": "portal.achievements.longtimeMember_desc", "icon": "Clock", "tier": 3, "xp_reward": 110, "threshold": 5, "condition_type": "member_years", "next_tier_id": "longtime_member_4", "secret": False, "sort_order": 187},
    {"id": "longtime_member_4", "category": "dedication", "name_key": "portal.achievements.longtimeMember", "description_key": "portal.achievements.longtimeMember_desc", "icon": "Clock", "tier": 4, "xp_reward": 220, "threshold": 10, "condition_type": "member_years", "next_tier_id": None, "secret": False, "sort_order": 188},

    # ═══ TITLED (equipped a title) ═══
    {"id": "titled_1", "category": "meta", "name_key": "portal.achievements.titled", "description_key": "portal.achievements.titled_desc", "icon": "BadgeCheck", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "title_equipped", "next_tier_id": None, "secret": False, "sort_order": 190},

    # ═══ REPORTER (tickets created) ═══
    {"id": "reporter_1", "category": "community", "name_key": "portal.achievements.reporter", "description_key": "portal.achievements.reporter_desc", "icon": "Flag", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "tickets_created", "next_tier_id": "reporter_2", "secret": False, "sort_order": 195},
    {"id": "reporter_2", "category": "community", "name_key": "portal.achievements.reporter", "description_key": "portal.achievements.reporter_desc", "icon": "Flag", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "tickets_created", "next_tier_id": "reporter_3", "secret": False, "sort_order": 196},
    {"id": "reporter_3", "category": "community", "name_key": "portal.achievements.reporter", "description_key": "portal.achievements.reporter_desc", "icon": "Flag", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "tickets_created", "next_tier_id": None, "secret": False, "sort_order": 197},

    # ═══ TIME TRAVELER (decades watched) ═══
    {"id": "time_traveler_1", "category": "diversity", "name_key": "portal.achievements.timeTraveler", "description_key": "portal.achievements.timeTraveler_desc", "icon": "Hourglass", "tier": 1, "xp_reward": 20, "threshold": 3, "condition_type": "decades_watched", "next_tier_id": "time_traveler_2", "secret": False, "sort_order": 200},
    {"id": "time_traveler_2", "category": "diversity", "name_key": "portal.achievements.timeTraveler", "description_key": "portal.achievements.timeTraveler_desc", "icon": "Hourglass", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "decades_watched", "next_tier_id": "time_traveler_3", "secret": False, "sort_order": 201},
    {"id": "time_traveler_3", "category": "diversity", "name_key": "portal.achievements.timeTraveler", "description_key": "portal.achievements.timeTraveler_desc", "icon": "Hourglass", "tier": 3, "xp_reward": 110, "threshold": 7, "condition_type": "decades_watched", "next_tier_id": None, "secret": False, "sort_order": 202},

    # ═══ FLIGHT HOURS (total watch hours) ═══
    {"id": "flight_time_1", "category": "watching", "name_key": "portal.achievements.flightTime", "description_key": "portal.achievements.flightTime_desc", "icon": "Timer", "tier": 1, "xp_reward": 20, "threshold": 100, "condition_type": "total_watch_hours", "next_tier_id": "flight_time_2", "secret": False, "sort_order": 210},
    {"id": "flight_time_2", "category": "watching", "name_key": "portal.achievements.flightTime", "description_key": "portal.achievements.flightTime_desc", "icon": "Timer", "tier": 2, "xp_reward": 50, "threshold": 500, "condition_type": "total_watch_hours", "next_tier_id": "flight_time_3", "secret": False, "sort_order": 211},
    {"id": "flight_time_3", "category": "watching", "name_key": "portal.achievements.flightTime", "description_key": "portal.achievements.flightTime_desc", "icon": "Timer", "tier": 3, "xp_reward": 110, "threshold": 1000, "condition_type": "total_watch_hours", "next_tier_id": "flight_time_4", "secret": False, "sort_order": 212},
    {"id": "flight_time_4", "category": "watching", "name_key": "portal.achievements.flightTime", "description_key": "portal.achievements.flightTime_desc", "icon": "Timer", "tier": 4, "xp_reward": 220, "threshold": 2500, "condition_type": "total_watch_hours", "next_tier_id": "flight_time_5", "secret": False, "sort_order": 213},
    {"id": "flight_time_5", "category": "watching", "name_key": "portal.achievements.flightTime", "description_key": "portal.achievements.flightTime_desc", "icon": "Timer", "tier": 5, "xp_reward": 500, "threshold": 5000, "condition_type": "total_watch_hours", "next_tier_id": "flight_time_6", "secret": False, "sort_order": 214},
    {"id": "flight_time_6", "category": "watching", "name_key": "portal.achievements.flightTime", "description_key": "portal.achievements.flightTime_desc", "icon": "Timer", "tier": 6, "xp_reward": 1200, "threshold": 10000, "condition_type": "total_watch_hours", "next_tier_id": None, "secret": False, "sort_order": 216},

    # ═══ AMBASSADOR (requests approved) ═══
    {"id": "ambassador_1", "category": "community", "name_key": "portal.achievements.ambassador", "description_key": "portal.achievements.ambassador_desc", "icon": "CheckCircle", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "requests_approved", "next_tier_id": "ambassador_2", "secret": False, "sort_order": 220},
    {"id": "ambassador_2", "category": "community", "name_key": "portal.achievements.ambassador", "description_key": "portal.achievements.ambassador_desc", "icon": "CheckCircle", "tier": 2, "xp_reward": 50, "threshold": 10, "condition_type": "requests_approved", "next_tier_id": "ambassador_3", "secret": False, "sort_order": 221},
    {"id": "ambassador_3", "category": "community", "name_key": "portal.achievements.ambassador", "description_key": "portal.achievements.ambassador_desc", "icon": "CheckCircle", "tier": 3, "xp_reward": 110, "threshold": 30, "condition_type": "requests_approved", "next_tier_id": None, "secret": False, "sort_order": 222},

    # ═══ COMPLETIONIST (finish all seasons of a series) ═══
    {"id": "completionist_1", "category": "watching", "name_key": "portal.achievements.completionist", "description_key": "portal.achievements.completionist_desc", "icon": "BookOpen", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "series_completed", "next_tier_id": "completionist_2", "secret": False, "sort_order": 230},
    {"id": "completionist_2", "category": "watching", "name_key": "portal.achievements.completionist", "description_key": "portal.achievements.completionist_desc", "icon": "BookOpen", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "series_completed", "next_tier_id": "completionist_3", "secret": False, "sort_order": 231},
    {"id": "completionist_3", "category": "watching", "name_key": "portal.achievements.completionist", "description_key": "portal.achievements.completionist_desc", "icon": "BookOpen", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "series_completed", "next_tier_id": "completionist_4", "secret": False, "sort_order": 232},
    {"id": "completionist_4", "category": "watching", "name_key": "portal.achievements.completionist", "description_key": "portal.achievements.completionist_desc", "icon": "BookOpen", "tier": 4, "xp_reward": 220, "threshold": 50, "condition_type": "series_completed", "next_tier_id": None, "secret": False, "sort_order": 233},

    # ═══ SPEED RUNNER (5 movies in one day) ═══
    {"id": "speed_runner_1", "category": "special", "name_key": "portal.achievements.speedRunner", "description_key": "portal.achievements.speedRunner_desc", "icon": "Rabbit", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "speed_runner", "next_tier_id": "speed_runner_2", "secret": False, "sort_order": 240},
    {"id": "speed_runner_2", "category": "special", "name_key": "portal.achievements.speedRunner", "description_key": "portal.achievements.speedRunner_desc", "icon": "Rabbit", "tier": 2, "xp_reward": 50, "threshold": 3, "condition_type": "speed_runner", "next_tier_id": "speed_runner_3", "secret": False, "sort_order": 241},
    {"id": "speed_runner_3", "category": "special", "name_key": "portal.achievements.speedRunner", "description_key": "portal.achievements.speedRunner_desc", "icon": "Rabbit", "tier": 3, "xp_reward": 110, "threshold": 5, "condition_type": "speed_runner", "next_tier_id": None, "secret": False, "sort_order": 242},

    # ═══ PALETTE MONDIALE (distinct countries via audio language) ═══
    {"id": "world_palette_1", "category": "diversity", "name_key": "portal.achievements.worldPalette", "description_key": "portal.achievements.worldPalette_desc", "icon": "MapPin", "tier": 1, "xp_reward": 20, "threshold": 5, "condition_type": "audio_languages", "next_tier_id": "world_palette_2", "secret": False, "sort_order": 250},
    {"id": "world_palette_2", "category": "diversity", "name_key": "portal.achievements.worldPalette", "description_key": "portal.achievements.worldPalette_desc", "icon": "MapPin", "tier": 2, "xp_reward": 50, "threshold": 10, "condition_type": "audio_languages", "next_tier_id": "world_palette_3", "secret": False, "sort_order": 251},
    {"id": "world_palette_3", "category": "diversity", "name_key": "portal.achievements.worldPalette", "description_key": "portal.achievements.worldPalette_desc", "icon": "MapPin", "tier": 3, "xp_reward": 110, "threshold": 20, "condition_type": "audio_languages", "next_tier_id": None, "secret": False, "sort_order": 252},

    # ═══ BINGE ABSOLU (10+ episodes in one session) ═══
    {"id": "absolute_binge_1", "category": "special", "name_key": "portal.achievements.absoluteBinge", "description_key": "portal.achievements.absoluteBinge_desc", "icon": "PlayCircle", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "binge_session", "next_tier_id": "absolute_binge_2", "secret": False, "sort_order": 260},
    {"id": "absolute_binge_2", "category": "special", "name_key": "portal.achievements.absoluteBinge", "description_key": "portal.achievements.absoluteBinge_desc", "icon": "PlayCircle", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "binge_session", "next_tier_id": "absolute_binge_3", "secret": False, "sort_order": 261},
    {"id": "absolute_binge_3", "category": "special", "name_key": "portal.achievements.absoluteBinge", "description_key": "portal.achievements.absoluteBinge_desc", "icon": "PlayCircle", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "binge_session", "next_tier_id": None, "secret": False, "sort_order": 262},

    # ═══ GENRE MASTER (100+ in a single genre) ═══
    {"id": "master_of_genre_1", "category": "watching", "name_key": "portal.achievements.masterOfGenre", "description_key": "portal.achievements.masterOfGenre_desc", "icon": "Layers", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "genre_master", "next_tier_id": "master_of_genre_2", "secret": False, "sort_order": 270},
    {"id": "master_of_genre_2", "category": "watching", "name_key": "portal.achievements.masterOfGenre", "description_key": "portal.achievements.masterOfGenre_desc", "icon": "Layers", "tier": 2, "xp_reward": 50, "threshold": 3, "condition_type": "genre_master", "next_tier_id": "master_of_genre_3", "secret": False, "sort_order": 271},
    {"id": "master_of_genre_3", "category": "watching", "name_key": "portal.achievements.masterOfGenre", "description_key": "portal.achievements.masterOfGenre_desc", "icon": "Layers", "tier": 3, "xp_reward": 110, "threshold": 5, "condition_type": "genre_master", "next_tier_id": None, "secret": False, "sort_order": 272},

    # ═══ ORGANIZER (events created via FAB) ═══
    {"id": "organizer_1", "category": "community", "name_key": "portal.achievements.organizer", "description_key": "portal.achievements.organizer_desc", "icon": "CalendarPlus", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "events_created", "next_tier_id": "organizer_2", "secret": False, "sort_order": 280},
    {"id": "organizer_2", "category": "community", "name_key": "portal.achievements.organizer", "description_key": "portal.achievements.organizer_desc", "icon": "CalendarPlus", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "events_created", "next_tier_id": "organizer_3", "secret": False, "sort_order": 281},
    {"id": "organizer_3", "category": "community", "name_key": "portal.achievements.organizer", "description_key": "portal.achievements.organizer_desc", "icon": "CalendarPlus", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "events_created", "next_tier_id": "organizer_4", "secret": False, "sort_order": 282},
    {"id": "organizer_4", "category": "community", "name_key": "portal.achievements.organizer", "description_key": "portal.achievements.organizer_desc", "icon": "CalendarPlus", "tier": 4, "xp_reward": 220, "threshold": 30, "condition_type": "events_created", "next_tier_id": None, "secret": False, "sort_order": 283},

    # ═══ LUCKY (surprise button via FAB) ═══
    {"id": "lucky_1", "category": "special", "name_key": "portal.achievements.lucky", "description_key": "portal.achievements.lucky_desc", "icon": "Dice5", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "surprise_used", "next_tier_id": "lucky_2", "secret": False, "sort_order": 290},
    {"id": "lucky_2", "category": "special", "name_key": "portal.achievements.lucky", "description_key": "portal.achievements.lucky_desc", "icon": "Dice5", "tier": 2, "xp_reward": 50, "threshold": 5, "condition_type": "surprise_used", "next_tier_id": "lucky_3", "secret": False, "sort_order": 291},
    {"id": "lucky_3", "category": "special", "name_key": "portal.achievements.lucky", "description_key": "portal.achievements.lucky_desc", "icon": "Dice5", "tier": 3, "xp_reward": 110, "threshold": 15, "condition_type": "surprise_used", "next_tier_id": "lucky_4", "secret": False, "sort_order": 292},
    {"id": "lucky_4", "category": "special", "name_key": "portal.achievements.lucky", "description_key": "portal.achievements.lucky_desc", "icon": "Dice5", "tier": 4, "xp_reward": 220, "threshold": 30, "condition_type": "surprise_used", "next_tier_id": None, "secret": False, "sort_order": 293},

    # ═══ CURATOR (public lists shared) ═══
    {"id": "curator_1", "category": "community", "name_key": "portal.achievements.curator", "description_key": "portal.achievements.curator_desc", "icon": "Bookmark", "tier": 1, "xp_reward": 20, "threshold": 1, "condition_type": "lists_public_created", "next_tier_id": "curator_2", "secret": False, "sort_order": 300},
    {"id": "curator_2", "category": "community", "name_key": "portal.achievements.curator", "description_key": "portal.achievements.curator_desc", "icon": "Bookmark", "tier": 2, "xp_reward": 50, "threshold": 3, "condition_type": "lists_public_created", "next_tier_id": "curator_3", "secret": False, "sort_order": 301},
    {"id": "curator_3", "category": "community", "name_key": "portal.achievements.curator", "description_key": "portal.achievements.curator_desc", "icon": "Bookmark", "tier": 3, "xp_reward": 110, "threshold": 7, "condition_type": "lists_public_created", "next_tier_id": "curator_4", "secret": False, "sort_order": 302},
    {"id": "curator_4", "category": "community", "name_key": "portal.achievements.curator", "description_key": "portal.achievements.curator_desc", "icon": "Bookmark", "tier": 4, "xp_reward": 220, "threshold": 15, "condition_type": "lists_public_created", "next_tier_id": "curator_5", "secret": False, "sort_order": 303},
    {"id": "curator_5", "category": "community", "name_key": "portal.achievements.curator", "description_key": "portal.achievements.curator_desc", "icon": "Bookmark", "tier": 5, "xp_reward": 500, "threshold": 30, "condition_type": "lists_public_created", "next_tier_id": None, "secret": False, "sort_order": 304},

    # ═══ LIBRARIAN (max items in a single list) ═══
    {"id": "librarian_1", "category": "community", "name_key": "portal.achievements.librarian", "description_key": "portal.achievements.librarian_desc", "icon": "Library", "tier": 1, "xp_reward": 20, "threshold": 10, "condition_type": "lists_max_items", "next_tier_id": "librarian_2", "secret": False, "sort_order": 310},
    {"id": "librarian_2", "category": "community", "name_key": "portal.achievements.librarian", "description_key": "portal.achievements.librarian_desc", "icon": "Library", "tier": 2, "xp_reward": 50, "threshold": 25, "condition_type": "lists_max_items", "next_tier_id": "librarian_3", "secret": False, "sort_order": 311},
    {"id": "librarian_3", "category": "community", "name_key": "portal.achievements.librarian", "description_key": "portal.achievements.librarian_desc", "icon": "Library", "tier": 3, "xp_reward": 110, "threshold": 50, "condition_type": "lists_max_items", "next_tier_id": "librarian_4", "secret": False, "sort_order": 312},
    {"id": "librarian_4", "category": "community", "name_key": "portal.achievements.librarian", "description_key": "portal.achievements.librarian_desc", "icon": "Library", "tier": 4, "xp_reward": 220, "threshold": 100, "condition_type": "lists_max_items", "next_tier_id": "librarian_5", "secret": False, "sort_order": 313},
    {"id": "librarian_5", "category": "community", "name_key": "portal.achievements.librarian", "description_key": "portal.achievements.librarian_desc", "icon": "Library", "tier": 5, "xp_reward": 500, "threshold": 250, "condition_type": "lists_max_items", "next_tier_id": None, "secret": False, "sort_order": 314},
]
