"""Variables available per template type — FR/EN."""

# Each key = list of variables the user can use in their template
TPL_VARS = {
    "fr": {
        "added_movie": [
            ("titre",       "Titre du film avec lien TMDB"),
            ("annee",       "Année de sortie"),
            ("synopsis",    "Synopsis (max 350 caractères)"),
            ("genres",      "Genres séparés par virgule"),
            ("note",        "Note TMDB /10"),
            ("duree",       "Durée en minutes"),
            ("tmdb",        "Lien Fiche TMDB"),
            ("imgur",       "Affiche du film"),
        ],
        "added_series": [
            ("titre",       "Titre de la série avec lien TMDB"),
            ("annee",       "Année de début"),
            ("synopsis",    "Synopsis"),
            ("genres",      "Genres"),
            ("note",        "Note TMDB /10"),
            ("nb_saisons",  "Nombre de saisons"),
            ("tmdb",        "Lien Fiche TMDB"),
            ("imgur",       "Affiche de la série"),
        ],
        "added_season": [
            ("titre_serie", "Nom de la série"),
            ("num_saison",  "Numéro de la saison (ex: 3)"),
            ("saison",      "Libellé saison (ex: Saison 3)"),
            ("nb_episodes", "Nombre d'épisodes"),
            ("annee",       "Année"),
            ("synopsis",    "Synopsis de la saison"),
            ("tmdb",        "Lien Fiche TMDB"),
            ("imgur",       "Affiche de la saison"),
        ],
        "added_episode": [
            ("titre_serie",  "Nom de la série"),
            ("titre_episode","Titre de l'épisode"),
            ("saison",       "Libellé saison (ex: Saison 3)"),
            ("episode",      "Libellé épisode (ex: Épisode 5)"),
            ("code",         "Code S03E05"),
            ("annee",        "Année"),
            ("synopsis",     "Synopsis de l'épisode"),
            ("tmdb",         "Lien Fiche TMDB"),
            ("imgur",        "Affiche de la série"),
        ],
        "added_grouped": [
            ("titre_serie",  "Nom de la série"),
            ("saison",       "Libellé saison (ex: Saison 3)"),
            ("nb_episodes",  "Nombre d'épisodes regroupés"),
            ("annee",        "Année"),
            ("tmdb",         "Lien Fiche TMDB"),
            ("imgur",        "Affiche de la série"),
        ],
        "server_offline": [
            ("nom_serveur",      "Nom du serveur Emby"),
            ("heure",            "Heure de détection"),
        ],
        "duplicate_found": [
            ("titre_media",  "Titre du média en doublon"),
            ("bibliotheque", "Bibliothèque Emby"),
            ("fichier_1",    "Chemin du premier fichier"),
            ("fichier_2",    "Chemin du second fichier"),
            ("taille_1",     "Taille du premier fichier"),
            ("taille_2",     "Taille du second fichier"),
        ],
        "request_new": [
            ("utilisateur",  "Nom de l'utilisateur"),
            ("titre_demande","Titre demandé"),
            ("type_media",   "Type : film ou série"),
            ("annee",        "Année"),
            ("date",         "Date de la demande"),
        ],
        "request_approved": [
            ("utilisateur",   "Nom de l'utilisateur"),
            ("titre_demande", "Titre demandé"),
            ("approuve_par",  "Administrateur ayant approuvé"),
        ],
        "request_available": [
            ("utilisateur",   "Nom de l'utilisateur"),
            ("titre_demande", "Titre demandé"),
            ("tmdb",          "Lien TMDB"),
        ],
        "request_partial": [
            ("utilisateur",   "Nom de l'utilisateur"),
            ("titre_demande", "Titre demandé"),
            ("dispo",         "Nombre d'épisodes disponibles"),
            ("total",         "Nombre total d'épisodes"),
        ],
        "request_rejected": [
            ("utilisateur",   "Nom de l'utilisateur"),
            ("titre_demande", "Titre demandé"),
            ("raison",        "Raison du rejet"),
        ],
        "issue_new": [
            ("utilisateur",    "Nom de l'utilisateur"),
            ("titre_media",    "Titre du média concerné"),
            ("type_probleme",  "Type de problème"),
            ("description",    "Description du problème"),
        ],
        "issue_comment": [
            ("utilisateur",  "Nom de l'utilisateur"),
            ("titre_media",  "Titre du média concerné"),
            ("commentaire",  "Texte du commentaire"),
        ],
        "issue_resolved": [
            ("titre_media",  "Titre du média concerné"),
            ("resolu_par",   "Administrateur ayant résolu"),
        ],
        "emby_alert": [
            ("type_alerte",  "Type d'alerte Emby"),
            ("message",      "Message de l'alerte"),
            ("severite",     "Sévérité : Info, Warning, Error"),
            ("heure",        "Heure de l'alerte"),
        ],
    },
    "en": {
        "added_movie": [
            ("title",       "Movie title with TMDB link"),
            ("year",        "Release year"),
            ("overview",    "Synopsis (max 350 chars)"),
            ("genres",      "Genres, comma-separated"),
            ("rating",      "TMDB rating /10"),
            ("runtime",     "Duration in minutes"),
            ("tmdb",        "TMDB page link"),
            ("imgur",       "Movie poster"),
        ],
        "added_series": [
            ("title",       "Series title with TMDB link"),
            ("year",        "Start year"),
            ("overview",    "Synopsis"),
            ("genres",      "Genres"),
            ("rating",      "TMDB rating /10"),
            ("seasons",     "Number of seasons"),
            ("tmdb",        "TMDB page link"),
            ("imgur",       "Series poster"),
        ],
        "added_season": [
            ("series_title","Series name"),
            ("season_number","Season number (e.g. 3)"),
            ("season",      "Season label (e.g. Season 3)"),
            ("episodes",    "Number of episodes"),
            ("year",        "Year"),
            ("overview",    "Season synopsis"),
            ("tmdb",        "TMDB page link"),
            ("imgur",       "Season poster"),
        ],
        "added_episode": [
            ("series_title", "Series name"),
            ("episode_title","Episode title"),
            ("season",       "Season label (e.g. Season 3)"),
            ("episode",      "Episode label (e.g. Episode 5)"),
            ("code",         "Code S03E05"),
            ("year",         "Year"),
            ("overview",     "Episode synopsis"),
            ("tmdb",         "TMDB page link"),
            ("imgur",        "Series poster"),
        ],
        "added_grouped": [
            ("series_title", "Series name"),
            ("season",       "Season label (e.g. Season 3)"),
            ("episodes",     "Number of grouped episodes"),
            ("year",         "Year"),
            ("tmdb",         "TMDB page link"),
            ("imgur",        "Series poster"),
        ],
        "server_offline": [
            ("server_name",  "Emby server name"),
            ("time",         "Detection time"),
        ],
        "duplicate_found": [
            ("media_title",  "Duplicate media title"),
            ("library",      "Emby library"),
            ("file_1",       "First file path"),
            ("file_2",       "Second file path"),
            ("size_1",       "First file size"),
            ("size_2",       "Second file size"),
        ],
        "request_new": [
            ("user",         "Username"),
            ("request_title","Requested title"),
            ("media_type",   "Type: movie or series"),
            ("year",         "Year"),
            ("date",         "Request date"),
        ],
        "request_approved": [
            ("user",          "Username"),
            ("request_title", "Requested title"),
            ("approved_by",   "Approved by"),
        ],
        "request_available": [
            ("user",          "Username"),
            ("request_title", "Requested title"),
            ("tmdb",          "TMDB link"),
        ],
        "request_partial": [
            ("user",          "Username"),
            ("request_title", "Requested title"),
            ("available",     "Available episodes"),
            ("total",         "Total episodes"),
        ],
        "request_rejected": [
            ("user",          "Username"),
            ("request_title", "Requested title"),
            ("reason",        "Rejection reason"),
        ],
        "issue_new": [
            ("user",           "Username"),
            ("media_title",    "Media title"),
            ("issue_type",     "Issue type"),
            ("description",    "Issue description"),
        ],
        "issue_comment": [
            ("user",         "Username"),
            ("media_title",  "Media title"),
            ("comment",      "Comment text"),
        ],
        "issue_resolved": [
            ("media_title",  "Media title"),
            ("resolved_by",  "Resolved by"),
        ],
        "emby_alert": [
            ("alert_type",   "Emby alert type"),
            ("message",      "Alert message"),
            ("severity",     "Severity: Info, Warning, Error"),
            ("time",         "Alert time"),
        ],
    },
}


def get_tpl_vars(lang: str = "en") -> dict:
    """Return the template variables for the given language."""
    return TPL_VARS.get(lang, TPL_VARS["en"])
