export const PREVIEW_SAMPLES = {
  added_movie: {
    titre: 'Inception',
    title: 'Inception',
    annee: '2010',
    year: '2010',
    synopsis: "Un voleur qui s'infiltre dans les rêves des autres...",
    overview: "Un voleur qui s'infiltre dans les rêves des autres...",
    genres: 'Sci-fi, Action',
    note: '8.4',
    rating: '8.4',
    duree: '148',
    runtime: '148',
    tmdb: 'Fiche TMDB',
    tmdb_url: 'https://www.themoviedb.org/movie/27205',
    poster: 'https://image.tmdb.org/t/p/w300/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    color: '#E8A735',
  },
  added_series: {
    titre: 'Breaking Bad',
    title: 'Breaking Bad',
    annee: '2008',
    year: '2008',
    synopsis: 'Un professeur de chimie devient dealer...',
    overview: 'Un professeur de chimie devient dealer...',
    genres: 'Drame, Crime',
    note: '9.5',
    rating: '9.5',
    nb_saisons: '5',
    seasons: '5',
    tmdb: 'Fiche TMDB',
    tmdb_url: 'https://www.themoviedb.org/tv/1396',
    poster: 'https://image.tmdb.org/t/p/w300/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    color: '#5865F2',
  },
  added_season: {
    titre: 'Breaking Bad — Saison 1',
    title: 'Breaking Bad — Saison 1',
    titre_serie: 'Breaking Bad',
    series_title: 'Breaking Bad',
    num_saison: '1',
    season_number: '1',
    saison: 'Saison 1',
    season: 'Saison 1',
    nb_episodes: '7',
    episodes: '7',
    annee: '2008',
    year: '2008',
    synopsis: 'La première saison de Breaking Bad...',
    overview: 'La première saison de Breaking Bad...',
    tmdb: 'Fiche TMDB',
    tmdb_url: 'https://www.themoviedb.org/tv/1396/season/1',
    poster: 'https://image.tmdb.org/t/p/w300/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    color: '#5865F2',
  },
  added_episode: {
    titre: 'Breaking Bad — S05E14',
    title: 'Breaking Bad — S05E14',
    titre_serie: 'Breaking Bad',
    series_title: 'Breaking Bad',
    titre_episode: 'Ozymandias',
    episode_title: 'Ozymandias',
    saison: 'Saison 5',
    season: 'Saison 5',
    episode: 'Épisode 14',
    code: 'S05E14',
    annee: '2013',
    year: '2013',
    synopsis: 'Walt prend la fuite...',
    overview: 'Walt prend la fuite...',
    tmdb: 'Fiche TMDB',
    tmdb_url: 'https://www.themoviedb.org/tv/1396/season/5/episode/14',
    poster: 'https://image.tmdb.org/t/p/w300/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    color: '#5865F2',
  },
  server_offline: {
    nom_serveur: 'Emby',
    server_name: 'Emby',
    heure: '03:42',
    time: '03:42',
    color: '#f87171',
  },
  duplicate_found: {
    titre_media: 'Inception (2010)',
    media_title: 'Inception (2010)',
    bibliotheque: 'Films',
    library: 'Films',
    fichier_1: '/films/Inception.mkv',
    file_1: '/films/Inception.mkv',
    fichier_2: '/films/Inception.2010.mkv',
    file_2: '/films/Inception.2010.mkv',
    taille_1: '12.4 GB',
    size_1: '12.4 GB',
    taille_2: '8.2 GB',
    size_2: '8.2 GB',
    color: '#fbbf24',
  },
  request_new: {
    utilisateur: 'alice',
    user: 'alice',
    username: 'alice',
    titre_demande: 'Dune Part 2',
    request_title: 'Dune Part 2',
    type_media: 'Film',
    media_type: 'Film',
    annee: '2024',
    year: '2024',
    date: '28 mars 2026',
    tmdb: '',
    color: '#60a5fa',
  },
  request_approved: {
    utilisateur: 'alice',
    user: 'alice',
    username: 'alice',
    titre_demande: 'Dune Part 2',
    request_title: 'Dune Part 2',
    approuve_par: 'admin',
    approved_by: 'admin',
    tmdb: '',
    color: '#22c55e',
  },
  request_available: {
    utilisateur: 'alice',
    user: 'alice',
    username: 'alice',
    titre_demande: 'Dune Part 2',
    request_title: 'Dune Part 2',
    tmdb: 'Fiche TMDB',
    color: '#22c55e',
  },
  request_partial: {
    utilisateur: 'alice',
    user: 'alice',
    username: 'alice',
    titre_demande: 'Breaking Bad',
    request_title: 'Breaking Bad',
    dispo: '3',
    available: '3',
    total: '5',
    color: '#fbbf24',
  },
  request_rejected: {
    utilisateur: 'alice',
    user: 'alice',
    username: 'alice',
    titre_demande: 'Film X',
    request_title: 'Film X',
    raison: 'Titre introuvable',
    reason: 'Titre introuvable',
    color: '#f87171',
  },
  issue_new: {
    utilisateur: 'bob',
    user: 'bob',
    username: 'bob',
    titre_media: 'Inception',
    media_title: 'Inception',
    type_probleme: 'Sous-titres manquants',
    issue_type: 'Sous-titres manquants',
    description: 'Pas de sous-titres FR',
    color: '#f87171',
  },
  issue_comment: {
    utilisateur: 'admin',
    user: 'admin',
    username: 'admin',
    titre_media: 'Inception',
    media_title: 'Inception',
    commentaire: 'Je regarde ça dès que possible.',
    comment: 'Je regarde ça dès que possible.',
    color: '#fbbf24',
  },
  issue_resolved: {
    titre_media: 'Inception',
    media_title: 'Inception',
    resolu_par: 'admin',
    resolved_by: 'admin',
    color: '#22c55e',
  },
  emby_alert: {
    type_alerte: 'Transcoding',
    alert_type: 'Transcoding',
    message: 'Limite atteinte',
    severite: 'Warning',
    severity: 'Warning',
    heure: '20:15',
    time: '20:15',
    color: '#fbbf24',
  },
  added_grouped: {
    titre_serie: 'Breaking Bad',
    series_title: 'Breaking Bad',
    saison: 'Saison 1',
    season: 'Season 1',
    nb_episodes: '7',
    episodes: '7',
    annee: '2008',
    year: '2008',
    tmdb: 'Fiche TMDB',
    tmdb_url: 'https://www.themoviedb.org/tv/1396/season/1',
    poster: 'https://image.tmdb.org/t/p/w300/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    color: '#06b6d4',
  },
}
